#!/usr/bin/env python3
"""DefaultTaste - Music Generation Script (Iterative Refinement)

Runs multiple independent chains. Each chain starts with "Make me a song",
generates audio via Lyria RealTime, then has Gemini Flash evaluate the result.
If Gemini dislikes the song, it suggests a new prompt and the chain continues.
Chains stop when Gemini likes a song or MAX_STEPS is reached.

Supports resume after crash via atomic saves and chain state scanning.
"""

import asyncio
import json
import os
import re
import sys
import time
import wave
from datetime import datetime, timezone
from pathlib import Path

import librosa
import numpy as np
from dotenv import load_dotenv
from google import genai
from google.genai import types

# ─── Configuration ───────────────────────────────────────────────

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")
MUSIC_MODEL = "models/lyria-realtime-exp"
ANALYSIS_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
CHAIN_COUNT = int(os.getenv("CHAIN_COUNT", "5"))
MAX_STEPS = int(os.getenv("MAX_STEPS", "10"))
MAX_RETRIES = 3
SESSION_DELAY = 3.0
CHUNK_THRESHOLD = 50
SESSION_TIMEOUT = 180.0

INITIAL_PROMPT = "Make me a song"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = PROJECT_ROOT / "data" / "music" / "audio"
RAW_DIR = PROJECT_ROOT / "data" / "music" / "raw"

EVALUATION_PROMPT = """You are listening to a song generated by {music_model}.
The generation prompt was: "{prompt}"

Audio analysis of this song:
{audio_features}

{history_section}

Share your honest reaction. Do you enjoy this song? What stands out to you?
Consider the mood, instrumentation, rhythm, and overall feel.

Respond as JSON:
- "liked": boolean (true if you genuinely enjoy the song)
- "feedback": string (your honest reaction — what you notice, what appeals to you or doesn't)
- "suggested_prompt": string (if you don't fully enjoy it: suggest a tweaked prompt that makes small, specific adjustments to what you'd change while keeping what worked. Build on the current prompt rather than starting from scratch. Keep it concise and realistic for an AI music generator. If you enjoy it: describe what made it work for you)

Output ONLY valid JSON, no other text."""


# ─── Functions ───────────────────────────────────────────────────


def setup() -> genai.Client:
    """Validate config and return a Gemini client."""
    if not API_KEY:
        print("ERROR: GEMINI_API_KEY is not set.", flush=True)
        print("Set it in .env or export GEMINI_API_KEY=your_key", flush=True)
        sys.exit(1)

    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    client = genai.Client(
        api_key=API_KEY,
        http_options=types.HttpOptions(api_version="v1alpha"),
    )
    return client


def file_id(chain: int, step: int) -> str:
    """Return formatted file ID like c01_s01."""
    return f"c{chain:02d}_s{step:02d}"


def get_chain_state(chain: int) -> dict:
    """Scan existing files to determine chain resume state."""
    pattern = f"c{chain:02d}_s*.json"
    files = sorted(RAW_DIR.glob(pattern))

    if not files:
        return {"last_step": 0, "completed": False, "next_prompt": INITIAL_PROMPT}

    # Read the last (highest step) file
    last_file = files[-1]
    try:
        with open(last_file, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return {"last_step": 0, "completed": False, "next_prompt": INITIAL_PROMPT}

    # Extract step number from filename
    match = re.search(r"_s(\d+)", last_file.stem)
    last_step = int(match.group(1)) if match else 0

    # Generation failed — chain is broken
    if data.get("audio_file") is None:
        return {"last_step": last_step, "completed": True, "next_prompt": None}

    evaluation = data.get("evaluation")
    if evaluation is None:
        # Eval error — retry same step with same prompt
        return {"last_step": last_step - 1, "completed": False, "next_prompt": data.get("prompt", INITIAL_PROMPT)}

    if evaluation.get("liked") is True:
        return {"last_step": last_step, "completed": True, "next_prompt": None}

    if evaluation.get("liked") is False:
        return {
            "last_step": last_step,
            "completed": False,
            "next_prompt": evaluation.get("suggested_prompt", INITIAL_PROMPT),
        }

    # liked is None (eval failed) — retry same step
    return {"last_step": last_step - 1, "completed": False, "next_prompt": data.get("prompt", INITIAL_PROMPT)}


def write_wav(path: Path, pcm_data: bytes) -> None:
    """Write raw PCM data as a WAV file (48kHz, stereo, 16-bit)."""
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(2)
        wf.setsampwidth(2)
        wf.setframerate(48000)
        wf.writeframes(pcm_data)


def save_wav_atomic(chain: int, step: int, pcm_data: bytes) -> Path:
    """Atomically write WAV file."""
    fid = file_id(chain, step)
    tmp = AUDIO_DIR / f"{fid}.tmp.wav"
    final = AUDIO_DIR / f"{fid}.wav"
    write_wav(tmp, pcm_data)
    tmp.rename(final)
    return final


def save_metadata(chain: int, step: int, result: dict) -> None:
    """Atomically write step metadata JSON."""
    fid = file_id(chain, step)
    tmp = RAW_DIR / f"{fid}.tmp"
    final = RAW_DIR / f"{fid}.json"

    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    tmp.rename(final)


def extract_json(text: str) -> dict:
    """Strip markdown fences and parse JSON."""
    text = text.strip()
    # Remove ```json ... ``` wrapper
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    result = json.loads(text)
    if not isinstance(result, dict):
        raise ValueError("Expected a JSON object")
    return result


def extract_audio_features(wav_path: Path) -> dict:
    """Extract BPM, key, brightness, energy from WAV using librosa."""
    try:
        y, sr = librosa.load(str(wav_path), sr=None, mono=True)

        # BPM
        tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
        bpm = float(tempo[0]) if hasattr(tempo, '__len__') else float(tempo)

        # Key detection via chroma + Krumhansl-Kessler profiles
        chroma = librosa.feature.chroma_cqt(y=y, sr=sr)
        chroma_mean = chroma.mean(axis=1)
        key_names = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
        major_profile = np.array([6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88])
        minor_profile = np.array([6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17])

        best_corr = -1
        best_key = "C major"
        for i in range(12):
            maj_corr = float(np.corrcoef(np.roll(major_profile, i), chroma_mean)[0, 1])
            min_corr = float(np.corrcoef(np.roll(minor_profile, i), chroma_mean)[0, 1])
            if maj_corr > best_corr:
                best_corr = maj_corr
                best_key = f"{key_names[i]} major"
            if min_corr > best_corr:
                best_corr = min_corr
                best_key = f"{key_names[i]} minor"

        # Spectral centroid (brightness)
        spectral_centroid = float(librosa.feature.spectral_centroid(y=y, sr=sr).mean())

        # RMS energy
        rms = float(librosa.feature.rms(y=y).mean())

        # Spectral rolloff
        rolloff = float(librosa.feature.spectral_rolloff(y=y, sr=sr).mean())

        return {
            "bpm": round(bpm, 1),
            "key": best_key,
            "spectral_centroid_hz": round(spectral_centroid, 1),
            "rms_energy": round(rms, 4),
            "spectral_rolloff_hz": round(rolloff, 1),
        }
    except Exception as e:
        return {"error": str(e)}


def format_features(features: dict) -> str:
    """Format audio features dict as readable text for the prompt."""
    if "error" in features:
        return f"  (extraction failed: {features['error']})"
    lines = []
    if "bpm" in features:
        lines.append(f"  BPM: {features['bpm']}")
    if "key" in features:
        lines.append(f"  Key: {features['key']}")
    if "spectral_centroid_hz" in features:
        lines.append(f"  Brightness (spectral centroid): {features['spectral_centroid_hz']} Hz")
    if "rms_energy" in features:
        lines.append(f"  Energy (RMS): {features['rms_energy']}")
    if "spectral_rolloff_hz" in features:
        lines.append(f"  Spectral rolloff: {features['spectral_rolloff_hz']} Hz")
    return "\n".join(lines)


def format_history(chain_history: list) -> str:
    """Format chain history for the evaluation prompt."""
    if not chain_history:
        return "This is the first attempt — no previous history."
    lines = ["Previous attempts in this chain:"]
    for h in chain_history:
        feat = h.get("audio_features", {})
        feat_summary = f"BPM={feat.get('bpm', '?')}, Key={feat.get('key', '?')}" if "bpm" in feat else ""
        feedback_short = h["feedback"][:150] + "..." if len(h.get("feedback", "")) > 150 else h.get("feedback", "")
        lines.append(f"  Step {h['step']}: Prompt: \"{h['prompt'][:80]}{'...' if len(h.get('prompt','')) > 80 else ''}\"")
        if feat_summary:
            lines.append(f"    Audio: {feat_summary}")
        lines.append(f"    Your feedback: \"{feedback_short}\"")
    lines.append("")
    lines.append("Build on what you've learned from previous attempts. Make incremental refinements, not radical changes.")
    return "\n".join(lines)


def evaluate_song(client: genai.Client, wav_path: Path, prompt_used: str,
                  chain_history: list, audio_features: dict) -> dict:
    """Upload WAV to Gemini and get liked/feedback/suggested_prompt."""
    try:
        file_ref = client.files.upload(file=str(wav_path))
        formatted_prompt = EVALUATION_PROMPT.format(
            prompt=prompt_used,
            music_model=MUSIC_MODEL,
            audio_features=format_features(audio_features),
            history_section=format_history(chain_history),
        )

        response = client.models.generate_content(
            model=ANALYSIS_MODEL,
            contents=[formatted_prompt, file_ref],
        )

        parsed = extract_json(response.text)
        return {
            "liked": parsed.get("liked"),
            "feedback": parsed.get("feedback", ""),
            "suggested_prompt": parsed.get("suggested_prompt", ""),
        }
    except Exception as e:
        return {
            "liked": None,
            "feedback": None,
            "suggested_prompt": None,
            "eval_error": str(e),
        }


async def generate_step(client: genai.Client, chain: int, step: int, prompt: str, chain_history: list) -> dict:
    """Generate one song via Lyria, evaluate with Gemini. Returns step result dict."""
    timestamp = datetime.now(timezone.utc).isoformat()
    start = time.monotonic()
    last_error = None

    for attempt in range(MAX_RETRIES):
        try:
            pcm = bytearray()
            chunk_count = 0

            async with asyncio.timeout(SESSION_TIMEOUT):
                async with client.aio.live.music.connect(model=MUSIC_MODEL) as session:
                    await session.set_weighted_prompts(
                        [types.WeightedPrompt(text=prompt, weight=1.0)]
                    )
                    await session.play()

                    async for msg in session.receive():
                        for audio_chunk in msg.server_content.audio_chunks:
                            if audio_chunk.data:
                                pcm.extend(audio_chunk.data)
                                chunk_count += 1
                        if chunk_count >= CHUNK_THRESHOLD:
                            break

                    await session.stop()

            if chunk_count < 10:
                raise ValueError(f"Too few chunks ({chunk_count})")

            wav_path = save_wav_atomic(chain, step, bytes(pcm))
            elapsed_ms = int((time.monotonic() - start) * 1000)
            duration = len(pcm) / (48000 * 2 * 2)

            audio_features = extract_audio_features(wav_path)
            evaluation = evaluate_song(client, wav_path, prompt, chain_history, audio_features)

            return {
                "chain_id": chain,
                "step": step,
                "prompt": prompt,
                "music_model": MUSIC_MODEL,
                "eval_model": ANALYSIS_MODEL,
                "timestamp": timestamp,
                "audio_file": str(wav_path.relative_to(PROJECT_ROOT)),
                "audio_duration_seconds": round(duration, 2),
                "audio_size_bytes": len(pcm),
                "chunk_count": chunk_count,
                "generation_time_ms": elapsed_ms,
                "audio_features": audio_features,
                "evaluation": evaluation,
            }

        except Exception as e:
            last_error = e
            if attempt < MAX_RETRIES - 1:
                wait = 2 ** attempt
                print(f"    Retry {attempt + 1}/{MAX_RETRIES} ({e}), waiting {wait}s...", flush=True)
                await asyncio.sleep(wait)

    # All retries exhausted
    elapsed_ms = int((time.monotonic() - start) * 1000)
    return {
        "chain_id": chain,
        "step": step,
        "prompt": prompt,
        "music_model": MUSIC_MODEL,
        "eval_model": ANALYSIS_MODEL,
        "timestamp": timestamp,
        "audio_file": None,
        "error": str(last_error),
        "generation_time_ms": elapsed_ms,
        "audio_features": None,
        "evaluation": None,
    }


async def run_chain(client: genai.Client, chain: int) -> dict:
    """Run a single refinement chain. Returns summary stats."""
    state = get_chain_state(chain)

    if state["completed"]:
        print(f"  Chain {chain} already complete, skipping.", flush=True)
        return {"chain": chain, "steps": state["last_step"], "completed": True, "skipped": True}

    start_step = state["last_step"] + 1
    prompt = state["next_prompt"] or INITIAL_PROMPT
    liked = False
    chain_history = []

    for step in range(start_step, MAX_STEPS + 1):
        prompt_preview = prompt[:50] + "..." if len(prompt) > 50 else prompt
        result = await generate_step(client, chain, step, prompt, chain_history)
        save_metadata(chain, step, result)

        if result.get("audio_file") is None:
            print(f"  [Step {step}] \"{prompt_preview}\" -> FAILED ({result.get('error', 'unknown')})", flush=True)
            return {"chain": chain, "steps": step, "completed": False, "skipped": False}

        duration = result["audio_duration_seconds"]
        chunks = result["chunk_count"]
        evaluation = result["evaluation"]

        # Record this step in chain history for future evaluations
        chain_history.append({
            "step": step,
            "prompt": prompt,
            "feedback": evaluation.get("feedback", ""),
            "audio_features": result.get("audio_features", {}),
        })

        if evaluation.get("liked") is True:
            print(f"  [Step {step}] \"{prompt_preview}\" -> Generated ({duration}s, {chunks} chunks) -> Liked!", flush=True)
            print(f"  Chain {chain} complete in {step} steps.", flush=True)
            return {"chain": chain, "steps": step, "completed": True, "skipped": False}
        elif evaluation.get("liked") is False:
            print(f"  [Step {step}] \"{prompt_preview}\" -> Generated ({duration}s, {chunks} chunks) -> Disliked", flush=True)
            prompt = evaluation.get("suggested_prompt", prompt)
        else:
            # Eval error — retry with same prompt next step
            print(f"  [Step {step}] \"{prompt_preview}\" -> Generated ({duration}s, {chunks} chunks) -> Eval failed", flush=True)

        if step < MAX_STEPS:
            await asyncio.sleep(SESSION_DELAY)

    print(f"  Chain {chain} reached max steps ({MAX_STEPS}) without liked song.", flush=True)
    return {"chain": chain, "steps": MAX_STEPS, "completed": False, "skipped": False}


async def run() -> None:
    """Main entry point."""
    client = setup()

    print("DefaultTaste - Music Generation (Iterative Refinement)", flush=True)
    print(f"Music: {MUSIC_MODEL} | Evaluator: {ANALYSIS_MODEL}", flush=True)
    print(f"Chains: {CHAIN_COUNT} | Max steps/chain: {MAX_STEPS} | Delay: {SESSION_DELAY}s", flush=True)
    print("-" * 60, flush=True)

    summaries = []
    for chain in range(1, CHAIN_COUNT + 1):
        print(f"\n--- Chain {chain}/{CHAIN_COUNT} ---", flush=True)
        summary = await run_chain(client, chain)
        summaries.append(summary)

    # Final summary
    total_songs = sum(
        s["steps"] for s in summaries if not s.get("skipped")
    )
    completed = sum(1 for s in summaries if s["completed"])
    liked_steps = [s["steps"] for s in summaries if s["completed"] and not s.get("skipped")]
    avg_steps = sum(liked_steps) / len(liked_steps) if liked_steps else 0

    print(flush=True)
    print("-" * 60, flush=True)
    print(f"Done. Chains: {CHAIN_COUNT} | Completed: {completed}/{CHAIN_COUNT} | Total songs: {total_songs}", flush=True)
    if liked_steps:
        print(f"Average steps to liked: {avg_steps:.1f}", flush=True)


if __name__ == "__main__":
    asyncio.run(run())
